credentials:
  usernames:
    abhishek:
      email: abhigore48@gmail.com
      failed_login_attempts: 0
      logged_in: False
      name: Abhishek Gore
      password: "passag"  # Change this password!
    prathamesh:
      email: gaikwadprathamesh479@gmail.com
      failed_login_attempts: 0
      logged_in: False
      name: prathamesh Gaikwad
      password: "passpg"
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:

  - melsby@gmail.com
