credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: False
      name: John Smith
      # This is the hash for "123"
      password: $2b$12$D.I.s/5/1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: False
      name: Rebecca Briggs
      # This is the hash for "456"
      password: $2b$12$E.2.s/5/2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
