credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: False
      name: John Smith
      password: "123"  # Change this password!
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: False
      name: Rebecca Briggs
      password: "456"
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com